### ISSUE TITLE
Building and installing on Windows

### ISSUE THREAD

**Issue by nxths** [sbidin/sdl2-ttf#1]
These bindings won't build + install on Windows currently due to a [bug involving GHC, Windows, and Template Haskell](https://github.com/haskell-game/sdl2/issues/41#issuecomment-73564593).  I made a [Windows branch](https://github.com/nxths/sdl2-ttf) with a crude workaround if anyone else is trying to do this.

**Comment by sbidin** [comment]
I hope this isn't an issue anymore, with the newer GHC.
