### ISSUE TITLE
Put on hackage please.

### ISSUE THREAD

**Issue by flomerz** [sbidin/sdl2-ttf#2]

**Comment by sbidin** [comment]
There's already an [sdl2-ttf package on Hackage](http://hackage.haskell.org/package/sdl2-ttf), it just doesn't work with the current version of the sdl2 package at the moment. You can find its repo [here](https://github.com/mankyKitty/sdl2-ttf). It differs greatly in its API from my version.

I wouldn't feel comfortable with uploading another sdl2-ttf binding to Hackage. There's been a lot of duplication of effort and I should have just contributed to @mankyKitty directly. The best option would probably be to fix Sean's sdl2-ttf so it works with sdl2 again.

**Comment by sbidin** [comment]
Actually, scratch that, I think Sean's sdl2-ttf works with sdl2 now.

**Comment by mankyKitty** [comment]
I'm currently not dog-fooding my own library, but I do pay attention when people send PRs and issues my way. So if there are things that you'd like to see then please shout out and I'll do what I can. :)

**Comment by flomerz** [comment]
Thanks for your responses.
I have a problem with @mankyKitty's version. I want to call this function:
```haskell
SDL.createTextureFromSurface
  :: transformers-0.4.2.0:Control.Monad.IO.Class.MonadIO m =>
     SDL.Renderer -> SDL.Surface -> m SDL.Texture
```

Which takes an SDL.Surface. But I get an SDL.Raw.Types.Surface.

```haskell
Font.renderTextSolid
  :: Graphics.UI.SDL.TTF.FFI.TTFFont
     -> String -> Color -> IO (GHC.Ptr.Ptr SDL.Raw.Types.Surface)
```

**Comment by sbidin** [comment]
If it helps, [this](https://github.com/sbidin/sdl2-ttf/blob/master/src/SDL/Font.hs#L192-L194) is how my version creates a `Surface`. You seem to be doing the same thing when you define `textSurface`.
